/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.OyenteMultiple;
import modelos.FormulasInterpolacion;

/**
 *
 * @author jarv
 */
public class PanelCampos extends javax.swing.JPanel {

    /**
     * Creates new form PanelNuevoCliente
     */
    public PanelCampos() {
        initComponents();
    }

    public void addEventos(OyenteMultiple oyente) {
        botonCalcular.addActionListener(oyente);
        gradoDos.addActionListener(oyente);
        gradoUno.addActionListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoGrados = new javax.swing.ButtonGroup();
        panelNorte = new javax.swing.JPanel();
        gradoDos = new javax.swing.JRadioButton();
        gradoUno = new javax.swing.JRadioButton();
        panelEtiquetas = new javax.swing.JPanel();
        etiquetaX0 = new javax.swing.JLabel();
        etiquetaF0 = new javax.swing.JLabel();
        etiquetaX1 = new javax.swing.JLabel();
        etiquetaF1 = new javax.swing.JLabel();
        etiquetaX2 = new javax.swing.JLabel();
        etiquetaF2 = new javax.swing.JLabel();
        etiquetaX = new javax.swing.JLabel();
        etiquetaF = new javax.swing.JLabel();
        panelCampos = new javax.swing.JPanel();
        campoX0 = new javax.swing.JTextField();
        campoF0 = new javax.swing.JTextField();
        campoX1 = new javax.swing.JTextField();
        campoF1 = new javax.swing.JTextField();
        campoX2 = new javax.swing.JTextField();
        campoF2 = new javax.swing.JTextField();
        campoX = new javax.swing.JTextField();
        campoF = new javax.swing.JTextField();
        panelSur = new javax.swing.JPanel();
        botonCalcular = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
        setLayout(new java.awt.BorderLayout());

        panelNorte.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        grupoGrados.add(gradoDos);
        gradoDos.setSelected(true);
        gradoDos.setText("Grado 2");
        gradoDos.setActionCommand("gradoDos");
        gradoDos.setName("gradoDos"); // NOI18N
        panelNorte.add(gradoDos);

        grupoGrados.add(gradoUno);
        gradoUno.setText("Grado 1");
        gradoUno.setActionCommand("gradoUno");
        gradoUno.setName("gradoUno"); // NOI18N
        panelNorte.add(gradoUno);

        add(panelNorte, java.awt.BorderLayout.NORTH);

        panelEtiquetas.setLayout(new java.awt.GridLayout(8, 1, 0, 15));

        etiquetaX0.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaX0.setText("X0");
        panelEtiquetas.add(etiquetaX0);

        etiquetaF0.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaF0.setText("F0");
        panelEtiquetas.add(etiquetaF0);

        etiquetaX1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaX1.setText("X1");
        panelEtiquetas.add(etiquetaX1);

        etiquetaF1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaF1.setText("F1");
        panelEtiquetas.add(etiquetaF1);

        etiquetaX2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaX2.setText("X2");
        panelEtiquetas.add(etiquetaX2);

        etiquetaF2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaF2.setText("F2");
        panelEtiquetas.add(etiquetaF2);

        etiquetaX.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaX.setText("X");
        panelEtiquetas.add(etiquetaX);

        etiquetaF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaF.setText("F");
        panelEtiquetas.add(etiquetaF);

        add(panelEtiquetas, java.awt.BorderLayout.WEST);

        panelCampos.setLayout(new java.awt.GridLayout(8, 1, 0, 15));

        campoX0.setColumns(10);
        campoX0.setName(""); // NOI18N
        panelCampos.add(campoX0);

        campoF0.setColumns(10);
        panelCampos.add(campoF0);

        campoX1.setColumns(10);
        panelCampos.add(campoX1);

        campoF1.setColumns(10);
        panelCampos.add(campoF1);

        campoX2.setColumns(10);
        panelCampos.add(campoX2);

        campoF2.setColumns(10);
        panelCampos.add(campoF2);

        campoX.setColumns(10);
        panelCampos.add(campoX);

        campoF.setEditable(false);
        campoF.setBackground(null);
        campoF.setColumns(10);
        campoF.setEnabled(false);
        panelCampos.add(campoF);

        add(panelCampos, java.awt.BorderLayout.CENTER);

        botonCalcular.setText("Realizar Calculo");
        botonCalcular.setName("calcular"); // NOI18N
        botonCalcular.setPreferredSize(new java.awt.Dimension(144, 40));
        panelSur.add(botonCalcular);

        add(panelSur, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the botonCalcular
     */
    public javax.swing.JButton getBotonCalcular() {
        return botonCalcular;
    }

    /**
     * @return the campoF0
     */
    public javax.swing.JTextField getCampoF0() {
        return campoF0;
    }

    /**
     * @return the campoF1
     */
    public javax.swing.JTextField getCampoF1() {
        return campoF1;
    }

    /**
     * @return the campoF2
     */
    public javax.swing.JTextField getCampoF2() {
        return campoF2;
    }

    /**
     * @return the campoX
     */
    public javax.swing.JTextField getCampoX() {
        return campoX;
    }

    /**
     * @return the campoX0
     */
    public javax.swing.JTextField getCampoX0() {
        return campoX0;
    }

    /**
     * @return the campoX1
     */
    public javax.swing.JTextField getCampoX1() {
        return campoX1;
    }

    /**
     * @return the campoX2
     */
    public javax.swing.JTextField getCampoX2() {
        return campoX2;
    }
    
    /**
     * @return the campoF
     */
    public javax.swing.JTextField getCampoF() {
        return campoF;
    }

    /**
     * @return the grupoGrados
     */
    public javax.swing.ButtonGroup getGrupoGrados() {
        return grupoGrados;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private javax.swing.JTextField campoF;
    private javax.swing.JTextField campoF0;
    private javax.swing.JTextField campoF1;
    private javax.swing.JTextField campoF2;
    private javax.swing.JTextField campoX;
    private javax.swing.JTextField campoX0;
    private javax.swing.JTextField campoX1;
    private javax.swing.JTextField campoX2;
    private javax.swing.JLabel etiquetaF;
    private javax.swing.JLabel etiquetaF0;
    private javax.swing.JLabel etiquetaF1;
    private javax.swing.JLabel etiquetaF2;
    private javax.swing.JLabel etiquetaX;
    private javax.swing.JLabel etiquetaX0;
    private javax.swing.JLabel etiquetaX1;
    private javax.swing.JLabel etiquetaX2;
    private javax.swing.JRadioButton gradoDos;
    private javax.swing.JRadioButton gradoUno;
    private javax.swing.ButtonGroup grupoGrados;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelEtiquetas;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSur;
    // End of variables declaration//GEN-END:variables

}
