/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.OyenteMultiple;
import modelos.FormulasInterpolacion;

/**
 *
 * @author jarv
 */
public class Ventana extends javax.swing.JFrame {
    
    private PanelCampos panelCampos;
    private PanelInterpolacion panelInterpolacion;
    private PanelPrincipal panelPrincipal = new PanelPrincipal();
    

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        
        panelCampos = new PanelCampos();
        FormulasInterpolacion interpolacion = new FormulasInterpolacion();
        OyenteMultiple oyente = new OyenteMultiple(interpolacion, this);
        panelInterpolacion = new PanelInterpolacion(interpolacion);
        this.addEventos(oyente);
        panelCampos.addEventos(oyente);
        panelPrincipal.getPanelCentro().add(panelInterpolacion, "Center");
        panelPrincipal.getPanelOeste().add(panelCampos, "West");
        this.add(panelPrincipal);
    }
    
    public void addEventos(OyenteMultiple oyente) {
        opcionSalir.addActionListener(oyente);
        opcionAcercaDe.addActionListener(oyente);
    }
    
    public void escribeModelo(String modelo){
        panelPrincipal.escribe(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        opcionSalir = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        opcionAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuArchivo.setText("Archivo");

        opcionSalir.setText("Salir");
        opcionSalir.setName("opcionSalir"); // NOI18N
        menuArchivo.add(opcionSalir);

        barraMenu.add(menuArchivo);

        menuAyuda.setText("Ayuda");

        opcionAcercaDe.setText("Acerca De");
        opcionAcercaDe.setName("opcionAcercaDe"); // NOI18N
        menuAyuda.add(opcionAcercaDe);

        barraMenu.add(menuAyuda);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the panelCampos
     */
    public vistas.PanelCampos getPanelCampos() {
        return panelCampos;
    }

    /**
     * @return the panelCentro
     */
    public javax.swing.JPanel getPanelInterpolacion() {
        return panelInterpolacion;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuItem opcionAcercaDe;
    private javax.swing.JMenuItem opcionSalir;
    // End of variables declaration//GEN-END:variables
}
